lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' 
    public_key:       '%kernel.project_dir%/config/jwt/public.pem' 
    pass_phrase:      'mje.espinpsa@gmail.com'
    token_ttl:        3600
