version: "3.8"

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_docker
    restart: on-failure
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/http.d/default.conf
      - ./src:/var/www/html
      - vendor:/var/www/html/vendor
      - var:/var/www/html/var

  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      #MYSQL_USER: myuser
      #MYSQL_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: mercure_docker
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeMe!mlkhjgfdklmjhgdfkjlmhgfklmdjmlklmkgjrzoijg"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeMe!mlkhjgfdklmjhgdfkjlmhgfklmdjmlklmkgjrzoijg"
      MERCURE_EXTRA_DIRECTIVES: cors_origins "http://localhost:3000"
    ports:
      - "9090:80"
      - "443:443"

  adminer:
    image: adminer
    restart: always
    ports:
      - 1333:8080

volumes:
  db-data:
  vendor:
  var:
